apiVersion: apps/v1
kind: Deployment
metadata:
  name: nix-foundation-www
  namespace: wiz-code-demo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nix-foundation-www
  template:
    metadata:
      labels:
        app: nix-foundation-www
    spec:
      containers:
      - image: danielmoloney/wiz-shift-left-demo-app:1.11
        name: nix-foundation-www
        ports:
        - containerPort: 8080
