apiVersion: v1
kind: Service
metadata:
  name: nix-foundation-www
  namespace: wiz-code-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nix-foundation-www
  type: LoadBalancer