name: 'build_release'

on:
  pull_request:
    types:
      - closed

jobs:
  wiz-cli-image-scan:
    if: github.event.pull_request.merged == true
    name: 'Build, Scan, and Push Image with Release'
    runs-on: self-hosted

    env:
      SCAN_PATH: "." # Set the relative path in the repo to build the image from
      REPOSITORY: docker.io/danielmoloney/wiz-shift-left-demo-app
      TAG: 1.${{ github.run_number }} # Set the tag to use for the image
      POLICY: "Default vulnerabilities policy - [dmoloney]" # Set the desired Wiz CLI policy to use

    defaults:
      run:
        shell: bash

    steps:
    # Step 1: Check out repository
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Download Wiz CLI
    - name: Download Wiz CLI
      run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

    # Step 4: Authenticate to Wiz
    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    # Step 5: Build the Docker image
    - name: Build the Docker image
      run: cd $SCAN_PATH && docker build . --tag $REPOSITORY:$TAG

    # Step 6: Run Wiz CLI docker image scan with release version as tag
    - name: Run wiz-cli docker image scan
      run: ./wizcli docker scan --image $REPOSITORY:$TAG --policy "$POLICY"

    # Step 7: Push the Docker image to the Docker Hub with release version as tag
    - name: Push the Docker image to the GitHub Container Registry
      run: |
        docker push $REPOSITORY:$TAG
        docker push $REPOSITORY:latest

    # Step 8: Fetch digest of Docker image for Graph enrichment
    - name: Fetch digest of Docker image for Graph enrichment
      run: ./wizcli docker tag --image $REPOSITORY:$TAG